"""Generates a professional PDF report for a saved calculation (SOP §8:
"Generate professional PDF" / "Download API").

Uses `reportlab` directly (canvas-level drawing) rather than a templating
layer — for a single-page, fixed-layout report like this, it keeps the
dependency footprint small and the output deterministic.
"""
from __future__ import annotations

import io
import uuid
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from app.core.exceptions import ForbiddenError, NotFoundError
from app.models.calculation import Calculation
from app.repositories.calculation_repository import CalculationRepository

_GOLD = colors.Color(0xC8 / 255, 0x9B / 255, 0x3C / 255)
_BLACK = colors.Color(0x12 / 255, 0x12 / 255, 0x12 / 255)
_GREY = colors.Color(0x66 / 255, 0x66 / 255, 0x66 / 255)


class PdfService:
    def __init__(self, repository: CalculationRepository) -> None:
        self._repository = repository

    async def generate_calculation_report(self, user_id: uuid.UUID, calculation_id: uuid.UUID) -> bytes:
        instance = await self._repository.get_by_id(calculation_id)
        if instance is None:
            raise NotFoundError("Calculation not found.")
        if instance.user_id != user_id:
            raise ForbiddenError("You do not have access to this calculation.")

        return self._render(instance)

    @staticmethod
    def _render(item: Calculation) -> bytes:
        buffer = io.BytesIO()
        page = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        margin = 20 * mm
        y = height - margin

        page.setFillColor(_GOLD)
        page.setFont("Helvetica-Bold", 20)
        page.drawString(margin, y, "Gold Value Calculator")

        page.setFillColor(_GREY)
        page.setFont("Helvetica", 10)
        now = datetime.now(UTC)
        page.drawRightString(width - margin, y, now.strftime("%d %b %Y"))
        page.drawRightString(width - margin, y - 14, now.strftime("%I:%M %p UTC"))

        y -= 10
        page.setStrokeColor(_GOLD)
        page.setLineWidth(1.5)
        page.line(margin, y, width - margin, y)
        y -= 30

        page.setFillColor(_BLACK)
        page.setFont("Helvetica-Bold", 15)
        page.drawString(margin, y, item.ornament_name)
        y -= 30

        rows = [
            ("Gross weight", f"{float(item.gross_weight):.3f} g"),
            ("Stone weight", f"{float(item.stone_weight):.3f} g"),
            ("Wastage", f"{float(item.wastage_percent):.2f}%"),
            ("Pure gold weight", f"{float(item.pure_gold_weight):.3f} g"),
            ("Purity", f"{float(item.purity) * 100:.1f}%"),
            ("Gold rate", f"Rs. {float(item.gold_rate):,.2f} / g"),
            (
                "Making charges",
                f"{float(item.making_charges_percent):.2f}%  "
                f"(Rs. {float(item.making_charges_amount):,.2f})",
            ),
            ("GST", f"{float(item.gst_percent):.2f}%  (Rs. {float(item.gst_amount):,.2f})"),
        ]

        page.setFont("Helvetica", 11)
        for label, value in rows:
            page.setFillColor(_GREY)
            page.drawString(margin, y, label)
            page.setFillColor(_BLACK)
            page.drawRightString(width - margin, y, value)
            y -= 20

        y -= 10
        page.setStrokeColor(colors.lightgrey)
        page.line(margin, y, width - margin, y)
        y -= 30

        box_top = y + 10
        box_height = 100
        page.setFillColor(colors.Color(0xF7 / 255, 0xF0 / 255, 0xE3 / 255))
        page.roundRect(margin, box_top - box_height, width - 2 * margin, box_height, 6, fill=1, stroke=0)

        inner_y = box_top - 22
        page.setFillColor(_GREY)
        page.setFont("Helvetica", 10)
        page.drawString(margin + 14, inner_y, "Total gold value")
        page.setFillColor(_BLACK)
        page.setFont("Helvetica-Bold", 18)
        page.drawString(margin + 14, inner_y - 22, f"Rs. {float(item.final_value):,.2f}")

        page.setFillColor(_GREY)
        page.setFont("Helvetica", 10)
        page.drawString(
            margin + 14, inner_y - 50, f"Estimated loan amount ({float(item.ltv_percent):.0f}% LTV)"
        )
        page.setFillColor(_GOLD)
        page.setFont("Helvetica-Bold", 15)
        page.drawString(margin + 14, inner_y - 72, f"Rs. {float(item.loan_amount):,.2f}")

        page.setFillColor(_GREY)
        page.setFont("Helvetica", 8)
        page.drawCentredString(width / 2, margin / 2, "Generated by Gold Value Calculator")

        page.showPage()
        page.save()
        buffer.seek(0)
        return buffer.read()
